ci:
  skip: [ggshield, terraform_fmt, terraform_validate, terraform_providers_lock]

repos:

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.42.0
  hooks:
    - id: markdownlint
      name: markdown linting

- repo: https://github.com/thlorenz/doctoc
  rev: v2.2.0
  hooks:
    - id: doctoc
      name: update toc

- repo: https://github.com/gitguardian/ggshield
  rev: v1.32.2
  hooks:
    - id: ggshield
      name: gitguardian scanning

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
      name: trailing whitespace
    - id: end-of-file-fixer
      name: end of file fixer
    - id: check-added-large-files
      name: check added large files
      args: ['--maxkb=650']
    - id: check-yaml
      name: check yaml
    - id: check-json
      name: check json

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.96.1
  hooks:
  - id: terraform_fmt
    name: terraform formatting
    args:
      - --args=-diff
      - --args=-write=true
  - id: terraform_validate
    name: terraform validation
    args:
      - --tf-init-args=-upgrade
      - --args=-json
  - id: terraform_providers_lock
    name: terraform providers lock
    args:
        - --hook-config=--mode=always-regenerate-lockfile
        - --args=-platform=linux_amd64
