version: 3

silent: true

includes:
  test: ./ops/taskfile.test.yaml
  prod: ./ops/taskfile.prod.yaml

tasks:
  init:
    desc: initialise local environment
    cmds:
      - tfenv pin &>/dev/null &
      - task: pre-commit:init

  pre-commit:init:
    desc: initialises pre-commit hooks
    cmds:
      - pre-commit install &>/dev/null &
